version: '3'

services:
  app:
    build: .
    ports:
      - "8000:8000"
      - "50051:50051"
      - "8080:8080"
    volumes:
      - .:/app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge